"""Initial schema

Revision ID: 1cf12b479c67
Revises: 
Create Date: 2026-04-25 11:15:25.556876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cf12b479c67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acl_policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('imperva_description', sa.Text(), nullable=True),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('custom_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_password_hash', sa.String(), nullable=True),
    sa.Column('api_id', sa.Text(), nullable=True),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('api_base_url', sa.String(), nullable=True),
    sa.Column('api_key_expired', sa.Boolean(), nullable=True),
    sa.Column('last_api_check', sa.DateTime(), nullable=True),
    sa.Column('setup_complete', sa.Boolean(), nullable=True),
    sa.Column('smtp_host', sa.String(), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_user', sa.String(), nullable=True),
    sa.Column('smtp_password', sa.Text(), nullable=True),
    sa.Column('smtp_from_address', sa.String(), nullable=True),
    sa.Column('smtp_use_tls', sa.Boolean(), nullable=True),
    sa.Column('poll_interval_seconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prefixes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imperva_asset_id', sa.String(), nullable=False),
    sa.Column('cidr', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('threshold_mbps', sa.Float(), nullable=True),
    sa.Column('threshold_kpps', sa.Float(), nullable=True),
    sa.Column('acl_policy_id', sa.String(), nullable=True),
    sa.Column('action_on_attack', sa.String(), nullable=True),
    sa.Column('notify_customer', sa.Boolean(), nullable=True),
    sa.Column('is_under_attack', sa.Boolean(), nullable=True),
    sa.Column('attack_started_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prefixes_id'), 'prefixes', ['id'], unique=False)
    op.create_index(op.f('ix_prefixes_imperva_asset_id'), 'prefixes', ['imperva_asset_id'], unique=True)
    op.create_table('attack_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefix_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('acl_applied', sa.Boolean(), nullable=True),
    sa.Column('acl_policy_id', sa.String(), nullable=True),
    sa.Column('peak_mbps', sa.Float(), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=True),
    sa.Column('imperva_event_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['prefix_id'], ['prefixes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attack_events_id'), 'attack_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attack_events_id'), table_name='attack_events')
    op.drop_table('attack_events')
    op.drop_index(op.f('ix_prefixes_imperva_asset_id'), table_name='prefixes')
    op.drop_index(op.f('ix_prefixes_id'), table_name='prefixes')
    op.drop_table('prefixes')
    op.drop_table('settings')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('acl_policies')
    # ### end Alembic commands ###
